before_install:
  - gem install bundler

rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.7
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
  - rbx
  - jruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.rails-master

matrix:
  exclude:
    # Rails 5.0 requires Ruby >= 2.2
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.0.x

    # Rails 5.1 requires Ruby >= 2.2
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.1.x

    # Rails 5.2 requires Ruby >= 2.2
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.2.x

    # Rails 6+ requires Ruby >= 2.5
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.2.8
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.3.7
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile.rails-master
  allow_failures:
    - rvm: rbx
  fast_finish: true
